function loadHandling(v)
	-- onibus
	if getElementModel(v) == 410 then
		setVehicleHandling(v, "mass", 2600)
		setVehicleHandling(v, "maxVelocity", 1500)
		setVehicleHandling(v, "engineAcceleration", 750)
		setVehicleHandling(v, "tractionLoss", 8.0)
	end	

	if getElementModel(v) == 579 then
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "maxVelocity", 120)
		setVehicleHandling(v, "engineAcceleration", 15)
		setVehicleHandling(v, "tractionLoss", 3.0)
		setVehicleHandling(v, "engineInertia", 25)

	end	

	if getElementModel(v) == 439 then
		setVehicleHandling(v, "maxVelocity", 320)
		setVehicleHandling(v, "engineAcceleration", 20)
		setVehicleHandling(v, "tractionLoss", 1.2)
		
	

	end	

	if getElementModel(v) == 419 then
		setVehicleHandling(v, "maxVelocity", 320)
		setVehicleHandling(v, "engineAcceleration", 20)
		setVehicleHandling(v, "tractionLoss", 1.2)
		
	

	end	


	

	if getElementModel(v) == 528 then
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 3000)
		setVehicleHandling(v, "dragCoeff", 1.8)
		setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 1.1)
		setVehicleHandling(v, "tractionLoss", 0.9)
		setVehicleHandling(v, "tractionBias", 0.497)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 260)
		setVehicleHandling(v, "engineAcceleration", 30)
		setVehicleHandling(v, "engineInertia", 50)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 50)
		setVehicleHandling(v, "ABS", false)
		setVehicleHandling(v, "steeringLock", 35)
		setVehicleHandling(v, "suspensionForceLevel", 1.8)
		setVehicleHandling(v, "suspensionDamping", 0.5)
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
		setVehicleHandling(v, "suspensionUpperLimit", 0.3)
		setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
		setVehicleHandling(v, "seatOffsetDistance", 0.2)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
		setVehicleHandling(v, "monetary", 25000)
		setVehicleHandling(v, "modelFlags", 0x40000001)
		setVehicleHandling(v, "handlingFlags", 0x10308803)
		setVehicleHandling(v, "headLight", 0)
		setVehicleHandling(v, "tailLight", 1)
		setVehicleHandling(v, "animGroup", 0)
	end




	if getElementModel(v) == 490 then
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 3000)
		setVehicleHandling(v, "dragCoeff", 1.8)
		setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 1.1)
		setVehicleHandling(v, "tractionLoss", 0.9)
		setVehicleHandling(v, "tractionBias", 0.497)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 260)
		setVehicleHandling(v, "engineAcceleration", 30)
		setVehicleHandling(v, "engineInertia", 50)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 50)
		setVehicleHandling(v, "ABS", false)
		setVehicleHandling(v, "steeringLock", 35)
		setVehicleHandling(v, "suspensionForceLevel", 1.8)
		setVehicleHandling(v, "suspensionDamping", 0.5)
		setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
		setVehicleHandling(v, "suspensionUpperLimit", 0.3)
		setVehicleHandling(v, "suspensionLowerLimit", -0.10)
		setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
		setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
		setVehicleHandling(v, "seatOffsetDistance", 0.2)
		setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
		setVehicleHandling(v, "monetary", 25000)
		setVehicleHandling(v, "modelFlags", 0x40000001)
		setVehicleHandling(v, "handlingFlags", 0x10308803)
		setVehicleHandling(v, "headLight", 0)
		setVehicleHandling(v, "tailLight", 1)
		setVehicleHandling(v, "animGroup", 0)
	end

			 -- PATAMO -> Ford Crown
			 if getElementModel(v) == 404 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 1.1)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 260)
				setVehicleHandling(v, "engineAcceleration", 30)
				setVehicleHandling(v, "engineInertia", 50)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1.8)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
				setVehicleHandling(v, "suspensionLowerLimit", -0.10)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
			end

			if getElementModel(v) == 588 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 1.1)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 260)
				setVehicleHandling(v, "engineAcceleration", 30)
				setVehicleHandling(v, "engineInertia", 50)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1.8)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
				setVehicleHandling(v, "suspensionLowerLimit", -0.10)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
			end

			if getElementModel(v) == 456 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 1.1)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 260)
				setVehicleHandling(v, "engineAcceleration", 30)
				setVehicleHandling(v, "engineInertia", 50)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1.8)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
				setVehicleHandling(v, "suspensionLowerLimit", -0.10)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
			end


			if getElementModel(v) == 604 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 1.1)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 260)
				setVehicleHandling(v, "engineAcceleration", 30)
				setVehicleHandling(v, "engineInertia", 50)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1.8)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
				setVehicleHandling(v, "suspensionLowerLimit", -0.10)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
			end

			if getElementModel(v) == 596 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 1.1)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 260)
				setVehicleHandling(v, "engineAcceleration", 30)
				setVehicleHandling(v, "engineInertia", 50)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1.8)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
				setVehicleHandling(v, "suspensionLowerLimit", -0.10)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
			end

			if getElementModel(v) == 597 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 1.1)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 260)
				setVehicleHandling(v, "engineAcceleration", 30)
				setVehicleHandling(v, "engineInertia", 50)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1.8)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
				setVehicleHandling(v, "suspensionLowerLimit", -0.10)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
			end

					
			
			-- BAC EB
			 if getElementModel(v) == 470 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 1.1)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 220)
				setVehicleHandling(v, "engineAcceleration", 15)
				setVehicleHandling(v, "engineInertia", 15)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 15)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1.8)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
				setVehicleHandling(v, "suspensionLowerLimit", -0.05)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
			end	
			
			-- ODR
			 if getElementModel(v) == 517 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 1.1)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 220)
				setVehicleHandling(v, "engineAcceleration", 15)
				setVehicleHandling(v, "engineInertia", 15)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 15)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1.8)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
				setVehicleHandling(v, "suspensionLowerLimit", -0.05)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
			end	
			
			 if getElementModel(v) == 518 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 1.1)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 200)
				setVehicleHandling(v, "engineAcceleration", 15)
				setVehicleHandling(v, "engineInertia", 15)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 15)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1.8)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
				setVehicleHandling(v, "suspensionLowerLimit", -0.05)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
			end	
			
			 if getElementModel(v) == 410 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 1.1)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 220)
				setVehicleHandling(v, "engineAcceleration", 15)
				setVehicleHandling(v, "engineInertia", 15)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 15)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1.8)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
				setVehicleHandling(v, "suspensionLowerLimit", -0.05)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
			end	
			
	 -- PCC		
			 if getElementModel(v) == 543 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 1.1)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 220)
				setVehicleHandling(v, "engineAcceleration", 15)
				setVehicleHandling(v, "engineInertia", 15)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 15)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1.8)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
				setVehicleHandling(v, "suspensionLowerLimit", -0.05)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
			end	

						 -- BAEP SW4 -> Ford Crown
			 if getElementModel(v) == 596 then
							setVehicleHandling(v, "mass", 1600)
							setVehicleHandling(v, "turnMass", 3000)
							setVehicleHandling(v, "dragCoeff", 1.8)
							setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
							setVehicleHandling(v, "percentSubmerged", 75)
							setVehicleHandling(v, "tractionMultiplier", 1.1)
							setVehicleHandling(v, "tractionLoss", 0.9)
							setVehicleHandling(v, "tractionBias", 0.497)
							setVehicleHandling(v, "numberOfGears", 5)
							setVehicleHandling(v, "maxVelocity", 220)
							setVehicleHandling(v, "engineAcceleration", 15)
							setVehicleHandling(v, "engineInertia", 15)
							setVehicleHandling(v, "driveType", "awd")
							setVehicleHandling(v, "engineType", "petrol")
							setVehicleHandling(v, "brakeDeceleration", 15)
							setVehicleHandling(v, "ABS", false)
							setVehicleHandling(v, "steeringLock", 35)
							setVehicleHandling(v, "suspensionForceLevel", 1.8)
							setVehicleHandling(v, "suspensionDamping", 0.5)
							setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
							setVehicleHandling(v, "suspensionUpperLimit", 0.3)
							setVehicleHandling(v, "suspensionLowerLimit", -0.05)
							setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
							setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
							setVehicleHandling(v, "seatOffsetDistance", 0.2)
							setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
							setVehicleHandling(v, "monetary", 25000)
							setVehicleHandling(v, "modelFlags", 0x40000001)
							setVehicleHandling(v, "handlingFlags", 0x10308803)
							setVehicleHandling(v, "headLight", 0)
							setVehicleHandling(v, "tailLight", 1)
							setVehicleHandling(v, "animGroup", 0)
			end	

			 if getElementModel(v) == 542 or getElementModel(v) == 576 then
							setVehicleHandling(v, "mass", 1600)
							setVehicleHandling(v, "turnMass", 3000)
							setVehicleHandling(v, "dragCoeff", 1.8)
							setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
							setVehicleHandling(v, "percentSubmerged", 75)
							setVehicleHandling(v, "tractionMultiplier", 1.1)
							setVehicleHandling(v, "tractionLoss", 0.9)
							setVehicleHandling(v, "tractionBias", 0.497)
							setVehicleHandling(v, "numberOfGears", 5)
							setVehicleHandling(v, "maxVelocity", 220)
							setVehicleHandling(v, "engineAcceleration", 15)
							setVehicleHandling(v, "engineInertia", 15)
							setVehicleHandling(v, "driveType", "awd")
							setVehicleHandling(v, "engineType", "petrol")
							setVehicleHandling(v, "brakeDeceleration", 15)
							setVehicleHandling(v, "ABS", false)
							setVehicleHandling(v, "steeringLock", 35)
							setVehicleHandling(v, "seatOffsetDistance", 0.2)
							setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
							setVehicleHandling(v, "monetary", 25000)
							setVehicleHandling(v, "modelFlags", 0x40000001)
							setVehicleHandling(v, "handlingFlags", 0x10308803)
							setVehicleHandling(v, "headLight", 0)
							setVehicleHandling(v, "tailLight", 1)
							setVehicleHandling(v, "animGroup", 0)
			end		

         -- FN

			 if getElementModel(v) == 479 then
							setVehicleHandling(v, "mass", 1600)
							setVehicleHandling(v, "turnMass", 3000)
							setVehicleHandling(v, "dragCoeff", 1.8)
							setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
							setVehicleHandling(v, "percentSubmerged", 75)
							setVehicleHandling(v, "tractionMultiplier", 1.1)
							setVehicleHandling(v, "tractionLoss", 0.9)
							setVehicleHandling(v, "tractionBias", 0.497)
							setVehicleHandling(v, "numberOfGears", 5)
							setVehicleHandling(v, "maxVelocity", 350)
							setVehicleHandling(v, "engineAcceleration", 25)
							setVehicleHandling(v, "engineInertia", 15)
							setVehicleHandling(v, "driveType", "awd")
							setVehicleHandling(v, "engineType", "petrol")
							setVehicleHandling(v, "brakeDeceleration", 15)
							setVehicleHandling(v, "ABS", false)
							setVehicleHandling(v, "steeringLock", 35)
							setVehicleHandling(v, "suspensionForceLevel", 1.8)
							setVehicleHandling(v, "suspensionDamping", 0.5)
							setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
							setVehicleHandling(v, "suspensionUpperLimit", 0.3)
							setVehicleHandling(v, "suspensionLowerLimit", -0.05)
							setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
							setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
							setVehicleHandling(v, "seatOffsetDistance", 0.2)
							setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
							setVehicleHandling(v, "monetary", 25000)
							setVehicleHandling(v, "modelFlags", 0x40000001)
							setVehicleHandling(v, "handlingFlags", 0x10308803)
							setVehicleHandling(v, "headLight", 0)
							setVehicleHandling(v, "tailLight", 1)
							setVehicleHandling(v, "animGroup", 0)
			end	

			 if getElementModel(v) == 418 then
							setVehicleHandling(v, "mass", 1600)
							setVehicleHandling(v, "turnMass", 3000)
							setVehicleHandling(v, "dragCoeff", 1.8)
							setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
							setVehicleHandling(v, "percentSubmerged", 75)
							setVehicleHandling(v, "tractionMultiplier", 1.1)
							setVehicleHandling(v, "tractionLoss", 0.9)
							setVehicleHandling(v, "tractionBias", 0.497)
							setVehicleHandling(v, "numberOfGears", 5)
							setVehicleHandling(v, "maxVelocity", 280)
							setVehicleHandling(v, "engineAcceleration", 20)
							setVehicleHandling(v, "engineInertia", 15)
							setVehicleHandling(v, "driveType", "awd")
							setVehicleHandling(v, "engineType", "petrol")
							setVehicleHandling(v, "brakeDeceleration", 15)
							setVehicleHandling(v, "ABS", false)
							setVehicleHandling(v, "steeringLock", 55)
							setVehicleHandling(v, "suspensionForceLevel", 1.8)
							setVehicleHandling(v, "suspensionDamping", 0.5)
							setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
							setVehicleHandling(v, "suspensionUpperLimit", 0.3)
							setVehicleHandling(v, "suspensionLowerLimit", -0.05)
							setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
							setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
							setVehicleHandling(v, "seatOffsetDistance", 0.2)
							setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
							setVehicleHandling(v, "monetary", 25000)
							setVehicleHandling(v, "modelFlags", 0x40000001)
							setVehicleHandling(v, "handlingFlags", 0x10308803)
							setVehicleHandling(v, "headLight", 0)
							setVehicleHandling(v, "tailLight", 1)
							setVehicleHandling(v, "animGroup", 0)
			end				
			
			 if getElementModel(v) == 604 then
							setVehicleHandling(v, "mass", 1600)
							setVehicleHandling(v, "turnMass", 3000)
							setVehicleHandling(v, "dragCoeff", 1.8)
							setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
							setVehicleHandling(v, "percentSubmerged", 75)
							setVehicleHandling(v, "tractionMultiplier", 1.1)
							setVehicleHandling(v, "tractionLoss", 0.9)
							setVehicleHandling(v, "tractionBias", 0.497)
							setVehicleHandling(v, "numberOfGears", 5)
							setVehicleHandling(v, "maxVelocity", 220)
							setVehicleHandling(v, "engineAcceleration", 15)
							setVehicleHandling(v, "engineInertia", 15)
							setVehicleHandling(v, "driveType", "awd")
							setVehicleHandling(v, "engineType", "petrol")
							setVehicleHandling(v, "brakeDeceleration", 15)
							setVehicleHandling(v, "ABS", false)
							setVehicleHandling(v, "steeringLock", 35)
							setVehicleHandling(v, "suspensionForceLevel", 1.8)
							setVehicleHandling(v, "suspensionDamping", 0.5)
							setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
							setVehicleHandling(v, "suspensionUpperLimit", 0.3)
							setVehicleHandling(v, "suspensionLowerLimit", -0.05)
							setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
							setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
							setVehicleHandling(v, "seatOffsetDistance", 0.2)
							setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
							setVehicleHandling(v, "monetary", 25000)
							setVehicleHandling(v, "modelFlags", 0x40000001)
							setVehicleHandling(v, "handlingFlags", 0x10308803)
							setVehicleHandling(v, "headLight", 0)
							setVehicleHandling(v, "tailLight", 1)
							setVehicleHandling(v, "animGroup", 0)
			end	

			 if getElementModel(v) == 516 then
							setVehicleHandling(v, "mass", 1600)
							setVehicleHandling(v, "turnMass", 3000)
							setVehicleHandling(v, "dragCoeff", 1.8)
							setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
							setVehicleHandling(v, "percentSubmerged", 75)
							setVehicleHandling(v, "tractionMultiplier", 1.1)
							setVehicleHandling(v, "tractionLoss", 0.9)
							setVehicleHandling(v, "tractionBias", 0.497)
							setVehicleHandling(v, "numberOfGears", 5)
							setVehicleHandling(v, "maxVelocity", 220)
							setVehicleHandling(v, "engineAcceleration", 15)
							setVehicleHandling(v, "engineInertia", 15)
							setVehicleHandling(v, "driveType", "awd")
							setVehicleHandling(v, "engineType", "petrol")
							setVehicleHandling(v, "brakeDeceleration", 15)
							setVehicleHandling(v, "ABS", false)
							setVehicleHandling(v, "steeringLock", 35)
							setVehicleHandling(v, "suspensionForceLevel", 1.8)
							setVehicleHandling(v, "suspensionDamping", 0.5)
							setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
							setVehicleHandling(v, "suspensionUpperLimit", 0.3)
							setVehicleHandling(v, "suspensionLowerLimit", -0.05)
							setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
							setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
							setVehicleHandling(v, "seatOffsetDistance", 0.2)
							setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
							setVehicleHandling(v, "monetary", 25000)
							setVehicleHandling(v, "modelFlags", 0x40000001)
							setVehicleHandling(v, "handlingFlags", 0x10308803)
							setVehicleHandling(v, "headLight", 0)
							setVehicleHandling(v, "tailLight", 1)
							setVehicleHandling(v, "animGroup", 0)
			end				
			
					 if getElementModel(v) == 458 then
							setVehicleHandling(v, "mass", 1600)
							setVehicleHandling(v, "turnMass", 3000)
							setVehicleHandling(v, "dragCoeff", 1.8)
							setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
							setVehicleHandling(v, "percentSubmerged", 75)
							setVehicleHandling(v, "tractionMultiplier", 1.1)
							setVehicleHandling(v, "tractionLoss", 0.9)
							setVehicleHandling(v, "tractionBias", 0.497)
							setVehicleHandling(v, "numberOfGears", 5)
							setVehicleHandling(v, "maxVelocity", 220)
							setVehicleHandling(v, "engineAcceleration", 15)
							setVehicleHandling(v, "engineInertia", 15)
							setVehicleHandling(v, "driveType", "awd")
							setVehicleHandling(v, "engineType", "petrol")
							setVehicleHandling(v, "brakeDeceleration", 15)
							setVehicleHandling(v, "ABS", false)
							setVehicleHandling(v, "steeringLock", 35)
							setVehicleHandling(v, "suspensionForceLevel", 1.8)
							setVehicleHandling(v, "suspensionDamping", 0.5)
							setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
							setVehicleHandling(v, "suspensionUpperLimit", 0.3)
							setVehicleHandling(v, "suspensionLowerLimit", -0.05)
							setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
							setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
							setVehicleHandling(v, "seatOffsetDistance", 0.2)
							setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
							setVehicleHandling(v, "monetary", 25000)
							setVehicleHandling(v, "modelFlags", 0x40000001)
							setVehicleHandling(v, "handlingFlags", 0x10308803)
							setVehicleHandling(v, "headLight", 0)
							setVehicleHandling(v, "tailLight", 1)
							setVehicleHandling(v, "animGroup", 0)
			end	
			
		-- PC VTR	

			 if getElementModel(v) == 438 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 1.1)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 260)
				setVehicleHandling(v, "engineAcceleration", 30)
				setVehicleHandling(v, "engineInertia", 50)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1.8)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
				setVehicleHandling(v, "suspensionLowerLimit", -0.10)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
			end
			
			 if getElementModel(v) == 438 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 1.1)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 260)
				setVehicleHandling(v, "engineAcceleration", 30)
				setVehicleHandling(v, "engineInertia", 50)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 50)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1.8)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
				setVehicleHandling(v, "suspensionLowerLimit", -0.10)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
			end		
			
			 if getElementModel(v) == 467 then
							setVehicleHandling(v, "mass", 1600)
							setVehicleHandling(v, "turnMass", 3000)
							setVehicleHandling(v, "dragCoeff", 1.8)
							setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
							setVehicleHandling(v, "percentSubmerged", 75)
							setVehicleHandling(v, "tractionMultiplier", 1.1)
							setVehicleHandling(v, "tractionLoss", 0.9)
							setVehicleHandling(v, "tractionBias", 0.497)
							setVehicleHandling(v, "numberOfGears", 5)
							setVehicleHandling(v, "maxVelocity", 220)
							setVehicleHandling(v, "engineAcceleration", 15)
							setVehicleHandling(v, "engineInertia", 15)
							setVehicleHandling(v, "driveType", "awd")
							setVehicleHandling(v, "engineType", "petrol")
							setVehicleHandling(v, "brakeDeceleration", 15)
							setVehicleHandling(v, "ABS", false)
							setVehicleHandling(v, "steeringLock", 35)
							setVehicleHandling(v, "suspensionForceLevel", 1.8)
							setVehicleHandling(v, "suspensionDamping", 0.5)
							setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
							setVehicleHandling(v, "suspensionUpperLimit", 0.3)
							setVehicleHandling(v, "suspensionLowerLimit", -0.05)
							setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
							setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
							setVehicleHandling(v, "seatOffsetDistance", 0.2)
							setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
							setVehicleHandling(v, "monetary", 25000)
							setVehicleHandling(v, "modelFlags", 0x40000001)
							setVehicleHandling(v, "handlingFlags", 0x10308803)
							setVehicleHandling(v, "headLight", 0)
							setVehicleHandling(v, "tailLight", 1)
							setVehicleHandling(v, "animGroup", 0)
			end



			 -- BAEP SW4 -> Ford Crown
			 if getElementModel(v) == 598 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 1.1)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 330)
				setVehicleHandling(v, "engineAcceleration", 40)
				setVehicleHandling(v, "engineInertia", 30)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 500)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1.8)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
				setVehicleHandling(v, "suspensionLowerLimit", -0.05)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
			end	

						 -- BAEP SW4 -> Ford Crown
			 if getElementModel(v) == 596 then
							setVehicleHandling(v, "mass", 1600)
							setVehicleHandling(v, "turnMass", 3000)
							setVehicleHandling(v, "dragCoeff", 1.8)
							setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
							setVehicleHandling(v, "percentSubmerged", 75)
							setVehicleHandling(v, "tractionMultiplier", 1.1)
							setVehicleHandling(v, "tractionLoss", 0.9)
							setVehicleHandling(v, "tractionBias", 0.497)
							setVehicleHandling(v, "numberOfGears", 5)
							setVehicleHandling(v, "maxVelocity", 220)
							setVehicleHandling(v, "engineAcceleration", 15)
							setVehicleHandling(v, "engineInertia", 15)
							setVehicleHandling(v, "driveType", "awd")
							setVehicleHandling(v, "engineType", "petrol")
							setVehicleHandling(v, "brakeDeceleration", 15)
							setVehicleHandling(v, "ABS", false)
							setVehicleHandling(v, "steeringLock", 35)
							setVehicleHandling(v, "suspensionForceLevel", 1.8)
							setVehicleHandling(v, "suspensionDamping", 0.5)
							setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
							setVehicleHandling(v, "suspensionUpperLimit", 0.3)
							setVehicleHandling(v, "suspensionLowerLimit", -0.05)
							setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
							setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
							setVehicleHandling(v, "seatOffsetDistance", 0.2)
							setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
							setVehicleHandling(v, "monetary", 25000)
							setVehicleHandling(v, "modelFlags", 0x40000001)
							setVehicleHandling(v, "handlingFlags", 0x10308803)
							setVehicleHandling(v, "headLight", 0)
							setVehicleHandling(v, "tailLight", 1)
							setVehicleHandling(v, "animGroup", 0)
			end	

		
			-- FT SW4 -> Ford Crown
			 if getElementModel(v) == 550 then
							setVehicleHandling(v, "mass", 1600)
							setVehicleHandling(v, "turnMass", 3000)
							setVehicleHandling(v, "dragCoeff", 1.8)
							setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
							setVehicleHandling(v, "percentSubmerged", 75)
							setVehicleHandling(v, "tractionMultiplier", 1.1)
							setVehicleHandling(v, "tractionLoss", 0.9)
							setVehicleHandling(v, "tractionBias", 0.497)
							setVehicleHandling(v, "numberOfGears", 5)
							setVehicleHandling(v, "maxVelocity", 220)
							setVehicleHandling(v, "engineAcceleration", 15)
							setVehicleHandling(v, "engineInertia", 15)
							setVehicleHandling(v, "driveType", "awd")
							setVehicleHandling(v, "engineType", "petrol")
							setVehicleHandling(v, "brakeDeceleration", 15)
							setVehicleHandling(v, "ABS", false)
							setVehicleHandling(v, "steeringLock", 35)
							setVehicleHandling(v, "suspensionForceLevel", 1.8)
							setVehicleHandling(v, "suspensionDamping", 0.5)
							setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
							setVehicleHandling(v, "suspensionUpperLimit", 0.3)
							setVehicleHandling(v, "suspensionLowerLimit", -0.05)
							setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
							setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
							setVehicleHandling(v, "seatOffsetDistance", 0.2)
							setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
							setVehicleHandling(v, "monetary", 25000)
							setVehicleHandling(v, "modelFlags", 0x40000001)
							setVehicleHandling(v, "handlingFlags", 0x10308803)
							setVehicleHandling(v, "headLight", 0)
							setVehicleHandling(v, "tailLight", 1)
							setVehicleHandling(v, "animGroup", 0)
			end
			if getElementModel(v) == 490 then
				setVehicleHandling(v, "mass", 1600)
				setVehicleHandling(v, "turnMass", 3000)
				setVehicleHandling(v, "dragCoeff", 1.8)
				setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
				setVehicleHandling(v, "percentSubmerged", 75)
				setVehicleHandling(v, "tractionMultiplier", 1.1)
				setVehicleHandling(v, "tractionLoss", 0.9)
				setVehicleHandling(v, "tractionBias", 0.497)
				setVehicleHandling(v, "numberOfGears", 5)
				setVehicleHandling(v, "maxVelocity", 220)
				setVehicleHandling(v, "engineAcceleration", 15)
				setVehicleHandling(v, "engineInertia", 15)
				setVehicleHandling(v, "driveType", "awd")
				setVehicleHandling(v, "engineType", "petrol")
				setVehicleHandling(v, "brakeDeceleration", 15)
				setVehicleHandling(v, "ABS", false)
				setVehicleHandling(v, "steeringLock", 35)
				setVehicleHandling(v, "suspensionForceLevel", 1.8)
				setVehicleHandling(v, "suspensionDamping", 0.5)
				setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
				setVehicleHandling(v, "suspensionUpperLimit", 0.3)
				setVehicleHandling(v, "suspensionLowerLimit", -0.05)
				setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
				setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
				setVehicleHandling(v, "seatOffsetDistance", 0.2)
				setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
				setVehicleHandling(v, "monetary", 25000)
				setVehicleHandling(v, "modelFlags", 0x40000001)
				setVehicleHandling(v, "handlingFlags", 0x10308803)
				setVehicleHandling(v, "headLight", 0)
				setVehicleHandling(v, "tailLight", 1)
				setVehicleHandling(v, "animGroup", 0)
end	


if getElementModel(v) == 400 then
	setVehicleHandling(v, "mass", 1600)
	setVehicleHandling(v, "turnMass", 3000)
	setVehicleHandling(v, "dragCoeff", 1.8)
	setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
	setVehicleHandling(v, "percentSubmerged", 75)
	setVehicleHandling(v, "tractionMultiplier", 1.1)
	setVehicleHandling(v, "tractionLoss", 0.9)
	setVehicleHandling(v, "tractionBias", 0.497)
	setVehicleHandling(v, "numberOfGears", 5)
	setVehicleHandling(v, "maxVelocity", 220)
	setVehicleHandling(v, "engineAcceleration", 15)
	setVehicleHandling(v, "engineInertia", 15)
	setVehicleHandling(v, "driveType", "awd")
	setVehicleHandling(v, "engineType", "petrol")
	setVehicleHandling(v, "brakeDeceleration", 15)
	setVehicleHandling(v, "ABS", false)
	setVehicleHandling(v, "steeringLock", 35)
	setVehicleHandling(v, "suspensionForceLevel", 1.8)
	setVehicleHandling(v, "suspensionDamping", 0.5)
	setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
	setVehicleHandling(v, "suspensionUpperLimit", 0.3)
	setVehicleHandling(v, "suspensionLowerLimit", -0.05)
	setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
	setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
	setVehicleHandling(v, "seatOffsetDistance", 0.2)
	setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
	setVehicleHandling(v, "monetary", 25000)
	setVehicleHandling(v, "modelFlags", 0x40000001)
	setVehicleHandling(v, "handlingFlags", 0x10308803)
	setVehicleHandling(v, "headLight", 0)
	setVehicleHandling(v, "tailLight", 1)
	setVehicleHandling(v, "animGroup", 0)
end	


if getElementModel(v) == 597 then
	setVehicleHandling(v, "mass", 1600)
	setVehicleHandling(v, "turnMass", 3000)
	setVehicleHandling(v, "dragCoeff", 1.8)
	setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
	setVehicleHandling(v, "percentSubmerged", 75)
	setVehicleHandling(v, "tractionMultiplier", 1.1)
	setVehicleHandling(v, "tractionLoss", 0.9)
	setVehicleHandling(v, "tractionBias", 0.497)
	setVehicleHandling(v, "numberOfGears", 5)
	setVehicleHandling(v, "maxVelocity", 220)
	setVehicleHandling(v, "engineAcceleration", 15)
	setVehicleHandling(v, "engineInertia", 15)
	setVehicleHandling(v, "driveType", "awd")
	setVehicleHandling(v, "engineType", "petrol")
	setVehicleHandling(v, "brakeDeceleration", 15)
	setVehicleHandling(v, "ABS", false)
	setVehicleHandling(v, "steeringLock", 35)
	setVehicleHandling(v, "suspensionForceLevel", 1.8)
	setVehicleHandling(v, "suspensionDamping", 0.5)
	setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
	setVehicleHandling(v, "suspensionUpperLimit", 0.3)
	setVehicleHandling(v, "suspensionLowerLimit", -0.05)
	setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
	setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
	setVehicleHandling(v, "seatOffsetDistance", 0.2)
	setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
	setVehicleHandling(v, "monetary", 25000)
	setVehicleHandling(v, "modelFlags", 0x40000001)
	setVehicleHandling(v, "handlingFlags", 0x10308803)
	setVehicleHandling(v, "headLight", 0)
	setVehicleHandling(v, "tailLight", 1)
	setVehicleHandling(v, "animGroup", 0)
end	

if getElementModel(v) == 529 then
	setVehicleHandling(v, "mass", 1600)
	setVehicleHandling(v, "turnMass", 3000)
	setVehicleHandling(v, "dragCoeff", 1.8)
	setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
	setVehicleHandling(v, "percentSubmerged", 75)
	setVehicleHandling(v, "tractionMultiplier", 1.1)
	setVehicleHandling(v, "tractionLoss", 0.9)
	setVehicleHandling(v, "tractionBias", 0.497)
	setVehicleHandling(v, "numberOfGears", 5)
	setVehicleHandling(v, "maxVelocity", 220)
	setVehicleHandling(v, "engineAcceleration", 15)
	setVehicleHandling(v, "engineInertia", 15)
	setVehicleHandling(v, "driveType", "awd")
	setVehicleHandling(v, "engineType", "petrol")
	setVehicleHandling(v, "brakeDeceleration", 15)
	setVehicleHandling(v, "ABS", false)
	setVehicleHandling(v, "steeringLock", 35)
	setVehicleHandling(v, "suspensionForceLevel", 1.8)
	setVehicleHandling(v, "suspensionDamping", 0.5)
	setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
	setVehicleHandling(v, "suspensionUpperLimit", 0.3)
	setVehicleHandling(v, "suspensionLowerLimit", -0.05)
	setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
	setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
	setVehicleHandling(v, "seatOffsetDistance", 0.2)
	setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
	setVehicleHandling(v, "monetary", 25000)
	setVehicleHandling(v, "modelFlags", 0x40000001)
	setVehicleHandling(v, "handlingFlags", 0x10308803)
	setVehicleHandling(v, "headLight", 0)
	setVehicleHandling(v, "tailLight", 1)
	setVehicleHandling(v, "animGroup", 0)
end

if getElementModel(v) == 421 then
	setVehicleHandling(v, "mass", 1600)
	setVehicleHandling(v, "turnMass", 3000)
	setVehicleHandling(v, "dragCoeff", 1.8)
	setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
	setVehicleHandling(v, "percentSubmerged", 75)
	setVehicleHandling(v, "tractionMultiplier", 1.1)
	setVehicleHandling(v, "tractionLoss", 0.9)
	setVehicleHandling(v, "tractionBias", 0.497)
	setVehicleHandling(v, "numberOfGears", 5)
	setVehicleHandling(v, "maxVelocity", 220)
	setVehicleHandling(v, "engineAcceleration", 15)
	setVehicleHandling(v, "engineInertia", 15)
	setVehicleHandling(v, "driveType", "awd")
	setVehicleHandling(v, "engineType", "petrol")
	setVehicleHandling(v, "brakeDeceleration", 15)
	setVehicleHandling(v, "ABS", false)
	setVehicleHandling(v, "steeringLock", 35)
	setVehicleHandling(v, "suspensionForceLevel", 1.8)
	setVehicleHandling(v, "suspensionDamping", 0.5)
	setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
	setVehicleHandling(v, "suspensionUpperLimit", 0.3)
	setVehicleHandling(v, "suspensionLowerLimit", -0.05)
	setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
	setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
	setVehicleHandling(v, "seatOffsetDistance", 0.2)
	setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
	setVehicleHandling(v, "monetary", 25000)
	setVehicleHandling(v, "modelFlags", 0x40000001)
	setVehicleHandling(v, "handlingFlags", 0x10308803)
	setVehicleHandling(v, "headLight", 0)
	setVehicleHandling(v, "tailLight", 1)
	setVehicleHandling(v, "animGroup", 0)
end

if getElementModel(v) == 566 then
	setVehicleHandling(v, "mass", 1600)
	setVehicleHandling(v, "turnMass", 3000)
	setVehicleHandling(v, "dragCoeff", 1.8)
	setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
	setVehicleHandling(v, "percentSubmerged", 75)
	setVehicleHandling(v, "tractionMultiplier", 1.1)
	setVehicleHandling(v, "tractionLoss", 0.9)
	setVehicleHandling(v, "tractionBias", 0.497)
	setVehicleHandling(v, "numberOfGears", 5)
	setVehicleHandling(v, "maxVelocity", 220)
	setVehicleHandling(v, "engineAcceleration", 15)
	setVehicleHandling(v, "engineInertia", 15)
	setVehicleHandling(v, "driveType", "awd")
	setVehicleHandling(v, "engineType", "petrol")
	setVehicleHandling(v, "brakeDeceleration", 15)
	setVehicleHandling(v, "ABS", false)
	setVehicleHandling(v, "steeringLock", 35)
	setVehicleHandling(v, "suspensionForceLevel", 1.8)
	setVehicleHandling(v, "suspensionDamping", 0.5)
	setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
	setVehicleHandling(v, "suspensionUpperLimit", 0.3)
	setVehicleHandling(v, "suspensionLowerLimit", -0.05)
	setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
	setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
	setVehicleHandling(v, "seatOffsetDistance", 0.2)
	setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
	setVehicleHandling(v, "monetary", 25000)
	setVehicleHandling(v, "modelFlags", 0x40000001)
	setVehicleHandling(v, "handlingFlags", 0x10308803)
	setVehicleHandling(v, "headLight", 0)
	setVehicleHandling(v, "tailLight", 1)
	setVehicleHandling(v, "animGroup", 0)
end

if getElementModel(v) == 547 then
	setVehicleHandling(v, "mass", 1600)
	setVehicleHandling(v, "turnMass", 3000)
	setVehicleHandling(v, "dragCoeff", 1.8)
	setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
	setVehicleHandling(v, "percentSubmerged", 75)
	setVehicleHandling(v, "tractionMultiplier", 1.1)
	setVehicleHandling(v, "tractionLoss", 0.9)
	setVehicleHandling(v, "tractionBias", 0.497)
	setVehicleHandling(v, "numberOfGears", 5)
	setVehicleHandling(v, "maxVelocity", 220)
	setVehicleHandling(v, "engineAcceleration", 15)
	setVehicleHandling(v, "engineInertia", 15)
	setVehicleHandling(v, "driveType", "awd")
	setVehicleHandling(v, "engineType", "petrol")
	setVehicleHandling(v, "brakeDeceleration", 15)
	setVehicleHandling(v, "ABS", false)
	setVehicleHandling(v, "steeringLock", 35)
	setVehicleHandling(v, "suspensionForceLevel", 1.8)
	setVehicleHandling(v, "suspensionDamping", 0.5)
	setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
	setVehicleHandling(v, "suspensionUpperLimit", 0.3)
	setVehicleHandling(v, "suspensionLowerLimit", -0.05)
	setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
	setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
	setVehicleHandling(v, "seatOffsetDistance", 0.2)
	setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
	setVehicleHandling(v, "monetary", 25000)
	setVehicleHandling(v, "modelFlags", 0x40000001)
	setVehicleHandling(v, "handlingFlags", 0x10308803)
	setVehicleHandling(v, "headLight", 0)
	setVehicleHandling(v, "tailLight", 1)
	setVehicleHandling(v, "animGroup", 0)
end	

if getElementModel(v) == 585 then
	setVehicleHandling(v, "mass", 1600)
	setVehicleHandling(v, "turnMass", 3000)
	setVehicleHandling(v, "dragCoeff", 1.8)
	setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
	setVehicleHandling(v, "percentSubmerged", 75)
	setVehicleHandling(v, "tractionMultiplier", 1.1)
	setVehicleHandling(v, "tractionLoss", 0.9)
	setVehicleHandling(v, "tractionBias", 0.497)
	setVehicleHandling(v, "numberOfGears", 5)
	setVehicleHandling(v, "maxVelocity", 220)
	setVehicleHandling(v, "engineAcceleration", 15)
	setVehicleHandling(v, "engineInertia", 15)
	setVehicleHandling(v, "driveType", "awd")
	setVehicleHandling(v, "engineType", "petrol")
	setVehicleHandling(v, "brakeDeceleration", 15)
	setVehicleHandling(v, "ABS", false)
	setVehicleHandling(v, "steeringLock", 35)
	setVehicleHandling(v, "suspensionForceLevel", 1.8)
	setVehicleHandling(v, "suspensionDamping", 0.5)
	setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
	setVehicleHandling(v, "suspensionUpperLimit", 0.3)
	setVehicleHandling(v, "suspensionLowerLimit", -0.05)
	setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
	setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
	setVehicleHandling(v, "seatOffsetDistance", 0.2)
	setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
	setVehicleHandling(v, "monetary", 25000)
	setVehicleHandling(v, "modelFlags", 0x40000001)
	setVehicleHandling(v, "handlingFlags", 0x10308803)
	setVehicleHandling(v, "headLight", 0)
	setVehicleHandling(v, "tailLight", 1)
	setVehicleHandling(v, "animGroup", 0)
end	

if getElementModel(v) == 458 then
	setVehicleHandling(v, "mass", 1600)
	setVehicleHandling(v, "turnMass", 3000)
	setVehicleHandling(v, "dragCoeff", 1.8)
	setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
	setVehicleHandling(v, "percentSubmerged", 75)
	setVehicleHandling(v, "tractionMultiplier", 1.1)
	setVehicleHandling(v, "tractionLoss", 0.9)
	setVehicleHandling(v, "tractionBias", 0.497)
	setVehicleHandling(v, "numberOfGears", 5)
	setVehicleHandling(v, "maxVelocity", 220)
	setVehicleHandling(v, "engineAcceleration", 15)
	setVehicleHandling(v, "engineInertia", 15)
	setVehicleHandling(v, "driveType", "awd")
	setVehicleHandling(v, "engineType", "petrol")
	setVehicleHandling(v, "brakeDeceleration", 15)
	setVehicleHandling(v, "ABS", false)
	setVehicleHandling(v, "steeringLock", 35)
	setVehicleHandling(v, "suspensionForceLevel", 1.8)
	setVehicleHandling(v, "suspensionDamping", 0.5)
	setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
	setVehicleHandling(v, "suspensionUpperLimit", 0.3)
	setVehicleHandling(v, "suspensionLowerLimit", -0.05)
	setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
	setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
	setVehicleHandling(v, "seatOffsetDistance", 0.2)
	setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
	setVehicleHandling(v, "monetary", 25000)
	setVehicleHandling(v, "modelFlags", 0x40000001)
	setVehicleHandling(v, "handlingFlags", 0x10308803)
	setVehicleHandling(v, "headLight", 0)
	setVehicleHandling(v, "tailLight", 1)
	setVehicleHandling(v, "animGroup", 0)
end	

if getElementModel(v) == 466 then
	setVehicleHandling(v, "mass", 1600)
	setVehicleHandling(v, "turnMass", 6000)
	setVehicleHandling(v, "dragCoeff", 1.8)
	setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
	setVehicleHandling(v, "percentSubmerged", 75)
	setVehicleHandling(v, "tractionMultiplier", 1.1)
	setVehicleHandling(v, "tractionLoss", 0.9)
	setVehicleHandling(v, "tractionBias", 0.497)
	setVehicleHandling(v, "numberOfGears", 5)
	setVehicleHandling(v, "maxVelocity", 260)
	setVehicleHandling(v, "engineAcceleration", 15)
	setVehicleHandling(v, "engineInertia", 15)
	setVehicleHandling(v, "driveType", "awd")
	setVehicleHandling(v, "engineType", "petrol")
	setVehicleHandling(v, "brakeDeceleration", 15)
	setVehicleHandling(v, "ABS", false)
	setVehicleHandling(v, "steeringLock", 35)
	setVehicleHandling(v, "suspensionForceLevel", 1.8)
	setVehicleHandling(v, "suspensionDamping", 0.5)
	setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
	setVehicleHandling(v, "suspensionUpperLimit", 0.3)
	setVehicleHandling(v, "suspensionLowerLimit", -0.05)
	setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
	setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
	setVehicleHandling(v, "seatOffsetDistance", 0.2)
	setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
	setVehicleHandling(v, "monetary", 25000)
	setVehicleHandling(v, "modelFlags", 0x40000001)
	setVehicleHandling(v, "handlingFlags", 0x10308803)
	setVehicleHandling(v, "headLight", 0)
	setVehicleHandling(v, "tailLight", 1)
	setVehicleHandling(v, "animGroup", 0)
end	


if getElementModel(v) == 426 then
	setVehicleHandling(v, "mass", 1600)
	setVehicleHandling(v, "turnMass", 6000)
	setVehicleHandling(v, "dragCoeff", 1.8)
	setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
	setVehicleHandling(v, "percentSubmerged", 75)
	setVehicleHandling(v, "tractionMultiplier", 1.1)
	setVehicleHandling(v, "tractionLoss", 0.9)
	setVehicleHandling(v, "tractionBias", 0.497)
	setVehicleHandling(v, "numberOfGears", 5)
	setVehicleHandling(v, "maxVelocity", 260)
	setVehicleHandling(v, "engineAcceleration", 15)
	setVehicleHandling(v, "engineInertia", 15)
	setVehicleHandling(v, "driveType", "awd")
	setVehicleHandling(v, "engineType", "petrol")
	setVehicleHandling(v, "brakeDeceleration", 15)
	setVehicleHandling(v, "ABS", false)
	setVehicleHandling(v, "steeringLock", 35)
	setVehicleHandling(v, "suspensionForceLevel", 1.8)
	setVehicleHandling(v, "suspensionDamping", 0.5)
	setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
	setVehicleHandling(v, "suspensionUpperLimit", 0.3)
	setVehicleHandling(v, "suspensionLowerLimit", -0.05)
	setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
	setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
	setVehicleHandling(v, "seatOffsetDistance", 0.2)
	setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
	setVehicleHandling(v, "monetary", 25000)
	setVehicleHandling(v, "modelFlags", 0x40000001)
	setVehicleHandling(v, "handlingFlags", 0x10308803)
	setVehicleHandling(v, "headLight", 0)
	setVehicleHandling(v, "tailLight", 1)
	setVehicleHandling(v, "animGroup", 0)
end	

if getElementModel(v) == 607 then
	setVehicleHandling(v, "mass", 1600)
	setVehicleHandling(v, "turnMass", 3000)
	setVehicleHandling(v, "dragCoeff", 1.8)
	setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
	setVehicleHandling(v, "percentSubmerged", 75)
	setVehicleHandling(v, "tractionMultiplier", 1.1)
	setVehicleHandling(v, "tractionLoss", 0.9)
	setVehicleHandling(v, "tractionBias", 0.497)
	setVehicleHandling(v, "numberOfGears", 5)
	setVehicleHandling(v, "maxVelocity", 220)
	setVehicleHandling(v, "engineAcceleration", 15)
	setVehicleHandling(v, "engineInertia", 15)
	setVehicleHandling(v, "driveType", "awd")
	setVehicleHandling(v, "engineType", "petrol")
	setVehicleHandling(v, "brakeDeceleration", 15)
	setVehicleHandling(v, "ABS", false)
	setVehicleHandling(v, "steeringLock", 35)
	setVehicleHandling(v, "suspensionForceLevel", 1.8)
	setVehicleHandling(v, "suspensionDamping", 0.5)
	setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
	setVehicleHandling(v, "suspensionUpperLimit", 0.3)
	setVehicleHandling(v, "suspensionLowerLimit", -0.05)
	setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
	setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
	setVehicleHandling(v, "seatOffsetDistance", 0.2)
	setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
	setVehicleHandling(v, "monetary", 25000)
	setVehicleHandling(v, "modelFlags", 0x40000001)
	setVehicleHandling(v, "handlingFlags", 0x10308803)
	setVehicleHandling(v, "headLight", 0)
	setVehicleHandling(v, "tailLight", 1)
	setVehicleHandling(v, "animGroup", 0)
end	

if getElementModel(v) == 507 then
	setVehicleHandling(v, "mass", 1600)
	setVehicleHandling(v, "turnMass", 3000)
	setVehicleHandling(v, "dragCoeff", 1.8)
	setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
	setVehicleHandling(v, "percentSubmerged", 75)
	setVehicleHandling(v, "tractionMultiplier", 1.1)
	setVehicleHandling(v, "tractionLoss", 0.9)
	setVehicleHandling(v, "tractionBias", 0.497)
	setVehicleHandling(v, "numberOfGears", 5)
	setVehicleHandling(v, "maxVelocity", 220)
	setVehicleHandling(v, "engineAcceleration", 15)
	setVehicleHandling(v, "engineInertia", 15)
	setVehicleHandling(v, "driveType", "awd")
	setVehicleHandling(v, "engineType", "petrol")
	setVehicleHandling(v, "brakeDeceleration", 15)
	setVehicleHandling(v, "ABS", false)
	setVehicleHandling(v, "steeringLock", 35)
	setVehicleHandling(v, "suspensionForceLevel", 1.8)
	setVehicleHandling(v, "suspensionDamping", 0.5)
	setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
	setVehicleHandling(v, "suspensionUpperLimit", 0.3)
	setVehicleHandling(v, "suspensionLowerLimit", -0.05)
	setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
	setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
	setVehicleHandling(v, "seatOffsetDistance", 0.2)
	setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
	setVehicleHandling(v, "monetary", 25000)
	setVehicleHandling(v, "modelFlags", 0x40000001)
	setVehicleHandling(v, "handlingFlags", 0x10308803)
	setVehicleHandling(v, "headLight", 0)
	setVehicleHandling(v, "tailLight", 1)
	setVehicleHandling(v, "animGroup", 0)
end	

if getElementModel(v) == 462 then
	setVehicleHandling(v, "mass", 5999)
	setVehicleHandling(v, "turnMass", 5999)
	setVehicleHandling(v, "maxVelocity", 350)
	setVehicleHandling(v, "engineAcceleration", 30)
	setVehicleHandling(v, "engineInertia", 5.0)
	setVehicleHandling(v, "engineType", "petrol")
	setVehicleHandling(v, "driveType", "fwd")
	setVehicleHandling(v, "steeringLock", 45.0)
	setVehicleHandling(v, "tractionMultiplier", 1.51)
	setVehicleHandling(v, "tractionLoss", 1.15)
	setVehicleHandling(v, "tractionBias", 0.5)
	setVehicleHandling(v, "brakeDeceleration", 31.0)
	setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
	setVehicleHandling(v, "dragCoeff",0.0)
 end


if getElementModel(v) == 523 then
	setVehicleHandling(v, "mass", 5999)
	setVehicleHandling(v, "turnMass", 5999)
	setVehicleHandling(v, "maxVelocity", 350)
	setVehicleHandling(v, "engineAcceleration", 30)
	setVehicleHandling(v, "engineInertia", 5.0)
	setVehicleHandling(v, "engineType", "petrol")
	setVehicleHandling(v, "driveType", "fwd")
	setVehicleHandling(v, "steeringLock", 45.0)
	setVehicleHandling(v, "tractionMultiplier", 1.51)
	setVehicleHandling(v, "tractionLoss", 1.15)
	setVehicleHandling(v, "tractionBias", 0.5)
	setVehicleHandling(v, "brakeDeceleration", 31.0)
	setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
	setVehicleHandling(v, "dragCoeff",0.0)
 end	
	

 if getElementModel(v) == 463 then
	setVehicleHandling(v, "mass", 5999)
	setVehicleHandling(v, "turnMass", 5999)
	setVehicleHandling(v, "maxVelocity", 350)
	setVehicleHandling(v, "engineAcceleration", 30)
	setVehicleHandling(v, "engineInertia", 5.0)
	setVehicleHandling(v, "engineType", "petrol")
	setVehicleHandling(v, "driveType", "fwd")
	setVehicleHandling(v, "steeringLock", 45.0)
	setVehicleHandling(v, "tractionMultiplier", 1.51)
	setVehicleHandling(v, "tractionLoss", 1.15)
	setVehicleHandling(v, "tractionBias", 0.5)
	setVehicleHandling(v, "brakeDeceleration", 31.0)
	setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
	setVehicleHandling(v, "dragCoeff",0.0)
 end

 if getElementModel(v) == 426 then
	setVehicleHandling(v, "mass", 1600)
	setVehicleHandling(v, "turnMass", 3000)
	setVehicleHandling(v, "dragCoeff", 1.8)
	setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
	setVehicleHandling(v, "percentSubmerged", 75)
	setVehicleHandling(v, "tractionMultiplier", 1.1)
	setVehicleHandling(v, "tractionLoss", 0.9)
	setVehicleHandling(v, "tractionBias", 0.497)
	setVehicleHandling(v, "numberOfGears", 5)
	setVehicleHandling(v, "maxVelocity", 220)
	setVehicleHandling(v, "engineAcceleration", 15)
	setVehicleHandling(v, "engineInertia", 15)
	setVehicleHandling(v, "driveType", "awd")
	setVehicleHandling(v, "engineType", "petrol")
	setVehicleHandling(v, "brakeDeceleration", 15)
	setVehicleHandling(v, "ABS", false)
	setVehicleHandling(v, "steeringLock", 35)
	setVehicleHandling(v, "suspensionForceLevel", 1.8)
	setVehicleHandling(v, "suspensionDamping", 0.5)
	setVehicleHandling(v, "suspensionHighSpeedDamping", 0.1)
	setVehicleHandling(v, "suspensionUpperLimit", 0.3)
	setVehicleHandling(v, "suspensionLowerLimit", -0.05)
	setVehicleHandling(v, "suspensionFrontRearBias", 0.55)
	setVehicleHandling(v, "suspensionAntiDiveMultiplier", 0.5)
	setVehicleHandling(v, "seatOffsetDistance", 0.2)
	setVehicleHandling(v, "collisionDamageMultiplier", 0.60)
	setVehicleHandling(v, "monetary", 25000)
	setVehicleHandling(v, "modelFlags", 0x40000001)
	setVehicleHandling(v, "handlingFlags", 0x10308803)
	setVehicleHandling(v, "headLight", 0)
	setVehicleHandling(v, "tailLight", 1)
	setVehicleHandling(v, "animGroup", 0)
end	

 if getElementModel(v) == 542 or getElementModel(v) == 576 then
     setVehiclePaintjob (v, 2 )
	 setVehicleColor(v, 0, 213, 255)
 end 

end

function loadHandlings()
	for k, v in ipairs(getElementsByType("vehicle")) do
		loadHandling(v)
	end
end
addEventHandler("onResourceStart", getResourceRootElement(getThisResource()), loadHandlings)

addEventHandler("onVehicleEnter", root, function(player)
    loadHandling(source)
end)


--[[
function resetHandling()
	 for k, v in ipairs(getElementsByType("vehicle")) do
		 for k1,v1 in ipairs(setModelHandling(getVehicleModel(v))) do
			-- setVehicleHandling(v, k1, nil)
		 end
	 end
 end
 addEventHandler("onResourceStop", getResourceRootElement(getThisResource()), resetHandling)]]--
 
 
 function currentTime(sourcePlayer)
    local timehour, timeminute = getTime()
    outputChatBox( "The current game time (server) is "..timehour..":"..timeminute, sourcePlayer )
end
addCommandHandler("gettime", currentTime)